### ISSUE TITLE
Clarify plugin purpose

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-cache#21]
@chesio Do you know https://github.com/emrikol/focus?
It is a WP **drop-in** implementation.

**Comment by szepeviktor** [comment]
Oh no!!

bc-cache is a Full Page cache, not an object cache.

**Comment by szepeviktor** [comment]
Could you update repo description/plugin description as follows?

Simple disk-based full page cache for WordPress inspired by Cachify.

**Comment by szepeviktor** [comment]
BTW Your code is highly clean.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by chesio** [comment]
Hi @szepeviktor,

I've updated plugin description, thanks for pointing out that BC Cache can be mistakenly taken as object cache plugin. I dropped the disk part though, I somehow dislike the term "disk-based" and disk caching is kind of default (unlike Redis, Memcache etc. where you need some specific software in addition and then it helps to mention it right away).

**Comment by szepeviktor** [comment]
> disk caching is kind of default

Actually if you have enough free memory linux will keep BC Cache files in its filesystem cache which is the maximum speed you can have:

- no disk access
- no protocol overhead (e.g. TCP and Redis)
- no PHP code or extra Apache module will be executed

**Comment by szepeviktor** [comment]
If you can afford to have a highly optimized WordPress installation and you have less than 1M page loads in month full page caching is not so useful.

So!

1. Have a sub-optimal WordPress installation without plugin code audit
1. Have 15M page loads
1. Install BC Cache!

**Comment by chesio** [comment]
Well, the goal of BC Cache (and all the similar plugins I took inspiration from like [Cachify](https://github.com/pluginkollektiv/cachify) or [Static File Cache](https://github.com/lochmueller/staticfilecache)) is to avoid PHP invocation and DB queries.

To be honest I have no idea how well WordPress (or TYPO3 for that matter) could be optimized, but I have all my projects on shared webhost and just by avoiding PHP invocation and DB access, the page download times drop from hundreds of ms to tens of ms.

**Comment by chesio** [comment]
Btw. thanks for pointing out that the cache files can be actually kept in memory, I haven't actually realized that. I'm not sure how much this happens on shared webhosts, but I guess at least `.htaccess` file is kept there, as it is being loaded with every request.

**Comment by szepeviktor** [comment]
> shared webhosting

... is a contradiction for me. It means no one [cares about running the site](https://github.com/szepeviktor/debian-server-tools/blob/master/CV.md).

**Comment by chesio** [comment]
I see your point, but this makes sense if you have a project with 1M+ visits per month as you suggested above. In the moment, I exclusively work on projects with hundreds or thousands visits per month... You're in a different league :-)

**Comment by szepeviktor** [comment]
> You're in a different league :-)

I would argue. When setting up infrastructure and WordPress I focus only a single visit per month, if its HTML is generated in ~0.2s then everything is okay: 100, 1000, 10 000 000 ...

**Comment by chesio** [comment]
Hi Viktor,

I think the discussion got a bit off-topic - if you want to continue it, feel free to shoot me an email :-) You can find my email address on my homepage.

Anyway, thanks again for the contributions to the plugin!
