### ISSUE TITLE
More sensitive cache flushing

### ISSUE THREAD

**Issue by chesio** [chesio/bc-cache#24]
Currently, the cache is automatically flushed on [`save_post`](https://developer.wordpress.org/reference/hooks/save_post/), [`edit_post`](https://developer.wordpress.org/reference/hooks/edit_post/), [`delete_post`](https://developer.wordpress.org/reference/hooks/delete_post/) and [`wp_trash_post`](https://developer.wordpress.org/reference/hooks/wp_trash_post/) actions, but these actions do not implicate front-end changes if related post type is only visible on back-end - [Flamingo](https://wordpress.org/plugins/flamingo/) inbound messages are one fine example.

It would be nice to have some way to prevent cache flushing in such cases.

**Comment by chesio** [comment]
> It would be nice to have some way to prevent cache flushing in such cases.

Any post type that is not public should be ignored when saved/edited/deleted/trashed.

**Comment by chesio** [comment]
See also: https://developer.wordpress.org/reference/functions/register_post_type/

**Comment by szepeviktor** [comment]
See https://github.com/szepeviktor/tiny-cache/blob/master/tiny-cache.php#L141-L181 too.
Only specific cache items are deleted with supplied `$post_id`.

**Comment by chesio** [comment]
Note: Cachify seems to flush the cache properly with regard to public posts - see `register_publish_hooks` method: https://github.com/pluginkollektiv/cachify/blob/master/inc/cachify.class.php#L890-L922
