### ISSUE TITLE
Many sources add a GET parameter

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-cache#26]
Cache skipping may be inappropriate when `!empty($_GET)`.

1. ~WordPress post ID ?p=~
1. Google Ads ?gclid= "Google Click Identifier"
1. All links on Facebook ?fbclid
1. Google Analytics tagging ?utm*
1. many others...

Please reconsider this.

**Comment by chesio** [comment]
Fair point. I guess a filter could be added to ignore specific query string variables when making this check.

I assume Google/Facebook (campaign) tracking identifiers can be ignored by default. I'm not sure about WordPress post ID - I give it a thought.

**Comment by szepeviktor** [comment]
Hard to be a FPC plugin manufaturer!

**Comment by chesio** [comment]
> Hard to be a FPC plugin manufacturer!

It's not - I like programming :-)

**Comment by chesio** [comment]
>     1. WordPress post ID ?p=

I just checked that on a website with pretty permalinks active, requests with `?p=` in URL are automatically redirected to pretty permalink version, so there is nothing to be done here.

**Comment by szepeviktor** [comment]
Some website may not use pretty links.

**Comment by szepeviktor** [comment]
Have you received my email? It is about a WooCommerce job.

**Comment by chesio** [comment]
> Have you received my email? It is about a WooCommerce job.

I did. I'm sorry I'm letting you wait, I'm going through quite busy period right now. I'll get to your emails over weekend.

**Comment by chesio** [comment]
> Some website may not use pretty links.

I decided to not support these on purpose as it makes things more complex and I didn't have any incentive to deal with the additional complexity (= have no site that do not use pretty permalinks).

Anyway, your suggestion to ignore tracking identifiers makes sense, so I'll keep this issue open.

**Comment by szepeviktor** [comment]
Okay, I am very-very weak on manufacturing software for non-professionals, for the masses.

So my [WAF](https://github.com/szepeviktor/waf4wordpress) has no UI.

**Comment by chesio** [comment]
> So my cache solution has no UI, and it is a `the_content`-only cache but is caches nav menus, widgets and translations too.

It's an interesting approach, I might try your cache in some future project.

**Comment by szepeviktor** [comment]
> It's an interesting approach, I might try your cache in some future project.

Okay @chesio ! Currently I develop `get_template_part()` caching.
