### ISSUE TITLE
Caching HTTP headers

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-cache#28]
Do you have a plan/opinion of HTTP headers?

1. Headers coming from WordPress core
1. Custom headers from themes and plugins

AFAIK Now they are lost.

**Comment by chesio** [comment]
Yeah, they are lost now.

If any special HTTP headers are required, they would have to be handled via `.htaccess` file. So far I have not missed this feature - do you have any example of plugin or WordPress core HTTP header that is lost due to this?

**Comment by szepeviktor** [comment]
> do you have any example of plugin or WordPress core HTTP header that is lost due to this?

You set "norobots" in Yoast SEO.

**Comment by szepeviktor** [comment]
Or let's say I'd like visitor to cache one of my pages with `Cache-Control:`

**Comment by szepeviktor** [comment]
Canonical `Link:` headers for CDN?

**Comment by szepeviktor** [comment]
# 🚀
